---
- name: SET IOS PROVIDER
  set_fact:
    provider:
      host: "{{hostvars[inventory_hostname]['ansible_host']}}"
      username: "{{ansible_username}}"
      password: "{{ansible_password}}"
      timeout: 120

- name: GET FACTS
  connection: local
  ios_facts:
    provider: "{{provider}}"
  register: result
- local_action: copy content="{{result}}" dest={{repo}}/facts.json

- name: GET DOMAIN NAME
  connection: local
  ios_command:
    provider: "{{provider}}"
    commands:
      - "show hosts"
    authorize: yes
  register: result
- local_action: copy content="{{result.stdout[0] | ios_domainname_filter}}" dest={{repo}}/domainname.txt

- name: EXECUTE CISCO_IOS ROLE
  connection: local
  ios_command:
    provider: "{{provider}}"
    commands:
      - "show version"
      - "show cdp neighbors"
      - "show cdp neighbors detail"
      - "show ip alias"
      - "show ip interface brief"
      - "show interfaces description"
      - "show ip route"
      - "show inventory"
      - "show running-config"
      - "show tech-support password"
    authorize: yes
  register: result
- local_action: copy content="{{result.stdout[0]}}\n" dest={{repo}}/show_version
- local_action: copy content="{{result.stdout[1]}}\n" dest={{repo}}/show_cdp_neighbors
- local_action: copy content="{{result.stdout[2]}}\n" dest={{repo}}/show_cdp_neighbors_detail
- local_action: copy content="{{result.stdout[2] | ios_cdp_filter}}" dest={{repo}}/cdp_neighbors.json
- local_action: copy content="{{result.stdout[3]}}\n" dest={{repo}}/show_ip_alias
- local_action: copy content="{{result.stdout[4]}}\n" dest={{repo}}/show_ip_interface_brief
- local_action: copy content="{{result.stdout[5]}}\n" dest={{repo}}/show_interfaces_description
- local_action: copy content="{{result.stdout[6]}}\n" dest={{repo}}/show_ip_route
- local_action: copy content="{{result.stdout[7]}}\n" dest={{repo}}/show_inventory
- local_action: copy content="{{result.stdout[8]}}\n" dest={{repo}}/running-config
- local_action: copy content="{{result.stdout[9]}}\n" dest={{repo}}/tech-support

